ezdan-admin/ViewModels/ContentViewModel.cs
using ezdan_entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ezdan_admin.ViewModels
{
    public class ContentViewModel
    {
        public int ContentId { get; set; }

        public int? ParentId { get; set; }

        [Required]
        public string ImageUrl { get; set; }

        [Required]
        public string Thumbnail { get; set; }

        [Required]
        public string EnglishTitle { get; set; }

        [Required]
        public string ArabicTitle { get; set; }

        [Required]
        public string ContentType { get; set; }

        [Required]
        public string EnglishDesc { get; set; }

        [Required]
        public string ArabicDesc { get; set; }

    }
}

ezdan-admin/Controllers/ContentsController.cs
using System.Data;
using System.IO;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ezdan_entities;
using ezdan_admin.ViewModels;
using System;
using System.Collections.Generic;
using System.Globalization;
using ezdan_logger;

namespace ezdan_admin.Controllers
{
    [Authorize]
    public class ContentsController : Controller
    {
        private Entities db;

        public ContentsController()
        {
            db = new Entities();
        }

        // GET: Contents
        public ActionResult Index(int? id)
        {
            if (id == null || id == 1 || id == 3 || id == 4 || id == 5 || id == 170) return RedirectToAction("Index", "Home");

            var content = db.Contents.Find(id);
            var contents = db.Contents.Include(c => c.Content2).Where(x => x.ParentId == id);
            ViewBag.CanDelete = false;

            if (id == 2 || id == 9 || id == 10 || id == 26 || id == 170 || id == 182)
            {
                if (id == 182 || id == 170 || id == 26 || id == 10 || id == 2)
                {
                    ViewBag.CanDelete = true;
                }
                ViewBag.CanCreate = true;
            }
            else
            {
                ViewBag.CanCreate = false;
            }

            switch(id)
            {
                case 2:
                    ViewBag.Title = "Promotions";
                    break;
                case 10:
                    ViewBag.Title = "Upcoming Events";
                    break;
                default:
                    ViewBag.Title = content.EnglishName;
                    break;
            }
            ViewBag.ContentIdTemp = content.ContentId;
            return View(contents.ToList());
        }

        // GET: Contents/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Content content = db.Contents.Find(id);
            if (content == null)
            {
                return HttpNotFound();
            }
            if (content.ParentId == 1 || content.ParentId == 3 || content.ParentId == 4 || content.ParentId == 5 || content.ParentId == 170)
            {
                return RedirectToAction("Index", "Home");
            }
            return View(content);
        }

        // GET: Contents/Create
        public ActionResult Create(int? id)
        {
            ViewBag.ParentId = new SelectList(db.Contents.Where(x => x.ContentId < 157), "ContentId", "EnglishName");
            switch (id)
            {
                //case 1:
                //    return RedirectToAction("CreateFaq", new { @id = id });
                case 2:
                    return RedirectToAction("CreateAnnouncement", new { @id = id });
                case 3:
                    return RedirectToAction("CreateAbout", new { @id = id });
                //case 4:
                //    return RedirectToAction("CreateClassified", new { @id = id });
                case 10:
                    return RedirectToAction("CreateEvent", new { @id = id });
                case 26:
                    return RedirectToAction("CreateEzdanPlus", new { @id = id });
                case 182:
                    return RedirectToAction("CreateSakinLocation", new { @id = id });
                default:
                    return RedirectToAction("Index", "Home");
            }
        }

        // GET: Contents/Create
        public ActionResult CreateFaq(int? id)
        {
            ViewBag.ParentId = new SelectList(db.Contents.Where(x => x.ContentId < 4), "ContentId", "EnglishName");
            return View();
        }

        // GET: Contents/Create
        public ActionResult CreateAnnouncement(int? id)
        {
            ViewBag.ParentId = new SelectList(db.Contents.Where(x => x.ContentId < 4), "ContentId", "EnglishName");
            return View();
        }

        // GET: Contents/Create
        public ActionResult CreateAbout(int? id)
        {
            ViewBag.ParentId = new SelectList(db.Contents.Where(x => x.ContentId < 4), "ContentId", "EnglishName");
            return View();
        }

        // GET: Contents/Create
        public ActionResult CreateClassified(int? id)
        {
            ViewBag.ParentId = new SelectList(db.Contents.Where(x => x.ContentId < 4), "ContentId", "EnglishName");
            return View();
        }

        // GET: Contents/Create
        public ActionResult CreateEzdanPlus(int? id)
        {
            ViewBag.ParentId = new SelectList(db.Contents.Where(x => x.ContentId < 27), "ContentId", "EnglishName");
            return View();
        }

        public ActionResult CreateFutureProject(int? id)
        {
            ViewBag.ParentId = new SelectList(db.Contents.Where(x => x.ContentId < 27), "ContentId", "EnglishName");
            return View();
        }

        // GET: Contents/Create
        public ActionResult CreateEvent(int? id)
        {
            ViewBag.ParentId = new SelectList(db.Contents.Where(x => x.ContentId < 27), "ContentId", "EnglishName");
            return View();
        }

        // GET: Contents/Create
        public ActionResult CreateSakinLocation(int? id)
        {
            ViewBag.ParentId = new SelectList(db.Contents.Where(x => x.ContentId < 27), "ContentId", "EnglishName");
            return View();
        }

        // POST: Contents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateFaq(ContentFaqViewModel contentFaq)
        {
            if (ModelState.IsValid)
            {
                Content content = new Content();
                content.ParentId = 1;
                content.ContentType = "textlist";
                content.EnglishName = contentFaq.EnglishQuestion;
                content.ArabicName = contentFaq.ArabicQuestion;
                content.CreatedOn = DateTime.UtcNow;
                db.Contents.Add(content);
                ContentProperty cp = new ContentProperty();
                cp.EnglishValue = contentFaq.EnglishAnswer;
                cp.ArabicValue = contentFaq.ArabicAnswer;
                cp.Content = content;
                cp.PropertyId = 1;
                db.ContentProperties.Add(cp);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ParentId = new SelectList(db.Contents.Where(x => x.ContentId < 4), "ContentId", "EnglishName", 1);
            return View(contentFaq);
        }

        // POST: Contents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateAnnouncement(ContentAnnounceViewModel contentAnnouncement)
        {
            if (ModelState.IsValid)
            {
                Content content = new Content();
                content.ParentId = 2;
                content.EnglishName = contentAnnouncement.EnglishTitle;
                content.ArabicName = contentAnnouncement.ArabicTitle;
                content.ContentType = "detailview";
                content.CreatedOn = DateTime.UtcNow;
                db.Contents.Add(content);

                ContentProperty image = new ContentProperty();
                var imagesDir = (ezdan_admin.Models.Enum.ContentImgsDir)content.ParentId;
                try
                {
                    HttpPostedFileBase imageFile = Request.Files[0];
                    image.EnglishValue = image.ArabicValue = SaveContentImage(imageFile, imagesDir.ToString());
                }
                catch (Exception e)
                {
                    LogManager.Log(LogType.error, e.Message, e);
                    ViewBag.imageProblem = true;
                    return View(contentAnnouncement);
                }
                image.Content = content;
                image.PropertyId = 3;

                ContentProperty thumb = new ContentProperty();
                try
                {
                    HttpPostedFileBase thumbFile = Request.Files[1];
                    thumb.EnglishValue = thumb.ArabicValue = SaveContentImage(thumbFile, imagesDir.ToString());
                }
                catch (Exception e)
                {
                    LogManager.Log(LogType.error, e.Message, e);
                    ViewBag.thumbProblem = true;
                    return View(contentAnnouncement);
                }
                thumb.Content = content;
                thumb.PropertyId = 4;

                ContentProperty details = new ContentProperty();
                details.EnglishValue = contentAnnouncement.EnglishDesc;
                details.ArabicValue = contentAnnouncement.ArabicDesc;
                details.Content = content;
                details.PropertyId = 1;

                db.ContentProperties.Add(image);
                db.ContentProperties.Add(thumb);
                db.ContentProperties.Add(details);

                try
                {
                    db.SaveChanges();
                }
                catch (DbEntityValidationException e)
                {
                    foreach (var eve in e.EntityValidationErrors)
                    {

ezdan-admin/Views/Contents/CreateAnnouncement.cshtml
@model ezdan_admin.ViewModels.ContentAnnounceViewModel

@{
    Layout = "~/Views/Shared/_ezdanLayout.cshtml";
}
@if (ViewBag.CanCreate != null && ViewBag.CanCreate != false)
{
    <h2>Create</h2>
}

@using (Html.BeginForm("CreateAnnouncement", "Contents", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>New Promotion</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.EnglishTitle, "English Title", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EnglishTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EnglishTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArabicTitle, "Arabic Title", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArabicTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArabicTitle, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr>

        <div class="form-group contentImg">
            @Html.LabelFor(model => model.ImageUrl, "Image", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="/Admin/Assets/images/home/placeholder.jpg" onerror="this.src='/Admin/Assets/images/home/placeholder.jpg'" style="height:20vh" />
                @Html.TextBoxFor(model => model.ImageUrl, new { type = "file", htmlAttributes = new { @class = "form-control contentImgSelector" } })
                @Html.ValidationMessageFor(model => model.ImageUrl, ViewBag.imageProblem == true ? "There was an error saving the image." : "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group contentImg">
            @Html.LabelFor(model => model.ThumbUrl, "Thumbnail", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="/Admin/Assets/images/home/placeholder.jpg" onerror="this.src='/Admin/Assets/images/home/placeholder.jpg'" style="height:20vh" />
                @Html.TextBoxFor(model => model.ThumbUrl, new { type = "file", htmlAttributes = new { @class = "form-control contentImgSelector" } })
                @Html.ValidationMessageFor(model => model.ThumbUrl, ViewBag.thumbProblem == true ? "There was an error saving the thumbnail image." : "", new { @class = "text-danger" })
            </div>
        </div>
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.EnglishDesc, "English Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.EnglishDesc, new { maxlength = 500, @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EnglishDesc, "", new { @class = "text-danger" })
                @*<div class="remaining-chars"><span>100</span> characters remaining</div>*@
            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArabicDesc, "Arabic Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.ArabicDesc, new { maxlength = 500, @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ArabicDesc, "", new { @class = "text-danger" })
                @*<div class="remaining-chars"><span>100</span> characters remaining</div>*@
            </div>
        </div>
        <hr>

        @*<div class="form-group">
            @Html.LabelFor(model => model.EnglishImageUrl, "English Image", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EnglishImageUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EnglishImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArabicImageUrl, "Arabic Image", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArabicImageUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArabicImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr>
        <div class="form-group">
            @Html.LabelFor(model => model.EnglishThumbnail, "English Thumbnail", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EnglishThumbnail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EnglishThumbnail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArabicThumbnail, "Arabic Thumbnail", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArabicThumbnail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArabicThumbnail, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr>

        <div class="form-group">
            @Html.LabelFor(model => model.EnglishDesc, "English Text", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EnglishDesc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EnglishDesc, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.ArabicDesc, "Arabic Text", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArabicDesc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArabicDesc, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

ezdan-admin/Views/Contents/CreateEvent.cshtml
@model ezdan_admin.ViewModels.ContentEventViewModel

@{
    Layout = "~/Views/Shared/_ezdanLayout.cshtml";
}
@if (ViewBag.CanCreate != null && ViewBag.CanCreate != false)
{
    <h2>Create</h2>
}

@using (Html.BeginForm("CreateEvent", "Contents", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>New Upcoming Event</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.EnglishTitle, "English Title", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EnglishTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EnglishTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArabicTitle, "Arabic Title", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArabicTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArabicTitle, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr>

        <div class="form-group contentImg">
            @Html.LabelFor(model => model.ImageUrl, "Image", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="/Admin/Assets/images/home/placeholder.jpg" onerror="this.src='/Admin/Assets/images/home/placeholder.jpg'" style="height:20vh" />
                @Html.TextBoxFor(model => model.ImageUrl, new { type = "file", htmlAttributes = new { @class = "form-control contentImgSelector" } })
                @Html.ValidationMessageFor(model => model.ImageUrl, ViewBag.imageProblem == true ? "There was an error saving the image." : "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group contentImg">
            @Html.LabelFor(model => model.ThumbUrl, "Thumbnail", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="/Admin/Assets/images/home/placeholder.jpg" onerror="this.src='/Admin/Assets/images/home/placeholder.jpg'" style="height:20vh" />
                @Html.TextBoxFor(model => model.ThumbUrl, new { type = "file", htmlAttributes = new { @class = "form-control contentImgSelector" } })
                @Html.ValidationMessageFor(model => model.ThumbUrl, ViewBag.thumbProblem == true ? "There was an error saving the thumbnail image." : "", new { @class = "text-danger" })
            </div>
        </div>
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.EnglishVenue, "English Venue", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EnglishVenue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EnglishVenue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArabicVenue, "Arabic Venue", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArabicVenue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArabicVenue, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr>

        <div class="form-group">
            @Html.LabelFor(model => model.EventStartingDate, "Starting Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventStartingDate, new { htmlAttributes = new { @class = "form-control", id = "startingdatetimepicker", type = "text" } })
                @Html.ValidationMessageFor(model => model.EventStartingDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.EventEndingDate, "Ending Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventEndingDate, new { htmlAttributes = new { @class = "form-control", id = "endingdatetimepicker", type = "text" } })
                @Html.ValidationMessageFor(model => model.EventEndingDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr>

        <div class="form-group">
            @Html.LabelFor(model => model.EnglishDesc, "English Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.EnglishDesc, new { maxlength = 500, @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EnglishDesc, "", new { @class = "text-danger" })
                @*<div class="remaining-chars"><span>100</span> characters remaining</div>*@
            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArabicDesc, "Arabic Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.ArabicDesc, new { maxlength = 500, @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ArabicDesc, "", new { @class = "text-danger" })
                @*<div class="remaining-chars"><span>100</span> characters remaining</div>*@
            </div>
        </div>
        <hr>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

ezdan-admin/Views/Contents/CreateEzdanPlus.cshtml
@model ezdan_admin.ViewModels.ContentEzdanPlusViewModel

@{
    Layout = "~/Views/Shared/_ezdanLayout.cshtml";
}
@if (ViewBag.CanCreate != null && ViewBag.CanCreate != false)
{
    <h2>Create</h2>
}

@using (Html.BeginForm("CreateEzdanPlus", "Contents", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>New Ezdan Plus</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.EnglishTitle, "English Title", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EnglishTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EnglishTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArabicTitle, "Arabic Title", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArabicTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArabicTitle, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr>

        <div class="form-group contentImg">
            @Html.LabelFor(model => model.ImageName, "Image", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="/Admin/Assets/images/home/placeholder.jpg" onerror="this.src='/Admin/Assets/images/home/placeholder.jpg'" style="height:20vh" />
                @Html.TextBoxFor(model => model.ImageName, new { type = "file", htmlAttributes = new { @class = "form-control contentImgSelector" } })
                @Html.ValidationMessageFor(model => model.ImageName, ViewBag.imageProblem == true ? "There was an error saving the image." : "", new { @class = "text-danger" })
                @*@if(ViewBag.imageProblem != null)
                {
                    <div>@ViewBag.imageProblem</div>
                }*@
            </div>
        </div>
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.EnglishDesc, "English Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.EnglishDesc, new { maxlength = 500, @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EnglishDesc, "", new { @class = "text-danger" })
                @*<div class="remaining-chars"><span>100</span> characters remaining</div>*@
            </div>
            
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArabicDesc, "Arabic Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.ArabicDesc, new { maxlength = 500, @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ArabicDesc, "", new { @class = "text-danger" })
                @*<div class="remaining-chars"><span>100</span> characters remaining</div>*@
            </div>
        </div>
        <hr>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

ezdan-admin/Views/Contents/CreateSakinLocation.cshtml
@model ezdan_admin.ViewModels.ContentSakinLocationViewModel

@{
    Layout = "~/Views/Shared/_ezdanLayout.cshtml";
}
@if (ViewBag.CanCreate != null && ViewBag.CanCreate != false)
{
    <h2>Create</h2>
}

@using (Html.BeginForm("CreateSakinLocation", "Contents", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>New Future Project</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.EnglishTitle, "English Title", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EnglishTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EnglishTitle, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ArabicTitle, "Arabic Title", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArabicTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArabicTitle, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr>
        @*<div class="form-group">
            <label class="col-sm-2 control-label"></label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="us3-address" placeholder="Enter a location" autocomplete="off">
            </div>
        </div>*@
        <div class="form-group">
            <label class="control-label col-md-2"></label>
            <div class="col-md-10">
                <input type="text" id="us3-address" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">
                Location
            </label>
            <div class="col-md-10">
                <div style="width:100%;height:400px" id="inspania-map"></div>
            </div>
        </div>
        <div class="form-group hidden">
            @Html.LabelFor(model => model.Latitude, "Latitude", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control", id = "latitude", type = "text" } })
                @Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
                @*<div class="remaining-chars"><span>100</span> characters remaining</div>*@
            </div>
        </div>
        <div class="form-group hidden">
            @Html.LabelFor(model => model.Longitude, "Longitude", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control", id = "longitude", type = "text" } })
                @Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
                @*<div class="remaining-chars"><span>100</span> characters remaining</div>*@
            </div>
        </div>
        <hr>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<script>
    
</script>